### Registro de usuario
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "ivan.martinez@live.u-tad.com",
  "password": "Password123"
}

### Validación del email
PUT http://localhost:3000/api/user/validation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGFhOTY3ZTIyZGIyMmJiYTI3MDVjZSIsImlhdCI6MTc0MjM4MzQ2MywiZXhwIjoxNzQyMzg3MDYzfQ.epPc0Rhz826Itx5YoKQp0UaAotq2CdH5hMDGbEC-yOI

{
  "code": "540812"
}

### Login de usuario
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "ivan.martinez@live.u-tad.com",
  "password": "Password123"
}

### Mandar email
POST http://localhost:3000/api/mail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGFhOTY3ZTIyZGIyMmJiYTI3MDVjZSIsImlhdCI6MTc0MjM4MzU5NCwiZXhwIjoxNzQyMzg3MTk0fQ.2g6pBjsjFQFwxfZPSVYcA19NkSaTCTRUhVqfvjzwyu8

{
  "subject": "Prueba",
  "text": "Este es un email de prueba desde Nodemailer",
  "to": "destinatario@example.com",
  "from": "tupu"
}