### Registro de usuario
POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123"
}

### Validación del email
PUT http://localhost:3000/validation
Content-Type: application/json
Authorization: Bearer YOUR_TOKEN_HERE

{
  "code": "123456"
}

